version: '3.8'

services:
  # MongoDB service using official image
  mongodb:
    image: mongo:latest
    container_name: todo-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: documents
    networks:
      - app-network

  spring-api:
    image: todo-api
    container_name: todo-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:rootpassword@mongodb:27017/documents?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network

  angular-app:
    image: todo-app
    container_name: todo-app
    ports:
      - "4200:4200"
    depends_on:
      - spring-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
